angular.module('app').config(['$stateProvider','$urlRouterProvider',function ($stateProvider,$urlRouterProvider) {
    $stateProvider.state('main',{
        url:'/main',
        templateUrl:'dist/view/main.html',
        controller:'mainCtrl'
    }).state('position',{
        url:'/position/:id',
        templateUrl:'dist/view/position.html',
        controller:'positionCtrl'
        }
    ).state('search',{
        url:'/search',
        templateUrl:'dist/view/search.html',
        controller:'searchCtrl'
    }).state('add',{
        url:'/add',
        templateUrl:'dist/view/add.html',
        controller:'addCtrl'
    })
    $urlRouterProvider.otherwise('add');
}])
